# Site settings
title: Leonides Jonguitud
twitter_username: JonguiLeo
name: Leonides Jonguitud

# Build settings - THESE ARE CRITICAL, DO NOT REMOVE
markdown: kramdown
highlighter: rouge
permalink: /:title/

# User specific content

# Personal info for sidebar
personal_info:
  location: "San Luis Potosí, México"
  education: "UASLP (2022 - Present)"
  languages: "🇪🇸 🇺🇸 🇩🇪"
  email: "your-email@example.com"


# Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/Argus-Magic
 - title: StackOverflow
   url: https://stackoverflow.com/users/23371241/argus-magic
 - title: LinkedIn
   url: https://www.linkedin.com/in/leonides-jonguitud-rodriguez-0a91a7184/

# Any buzzword skills you want to include
skills:
 - C/C++
 - Python
 - x86 Assembly
 - Number Analysis
 - Autodesk EAGLE
 - Wolfram Mathematica 14.1
 - PCB design
 - Analog Circuitry
 - Analytical problem solving
 - Communication and project management
 - Linux familiarity
 - Gen. AI knowledge

# Blogfeed is optional - COMMENTED OUT since you don't have a blog
# blogfeed: https://automateddeveloper.blogspot.com/feeds/posts/default?alt=json

# Work experience is required
roles:
 - title: Freelance personal tutor
   start: 2022
   end: Ongoing
   employer: Self-employed
   description: Offered private tutoring services for elementary, middle, high school and University level students across all fields of knowledge including but not limited to Mathematics, Physics, Chemistry, Biology, Computer Science, Engineering and Business.

# Education is required
education:
 - level: High School Diploma
   date: 2022
   subject: High School Mathematics and Science
   school: Harkness Institute, San Luis Potosí, México

# List of interesting Github repo/projects to include - optional
github:
 - Argus-Magic/Plantilla-Reporte-IICO
 - Argus-Magic/Signal_Analysis
 - Argus-Magic/yt-dlp-helper

# Stackoverflow flair is optional
stackoverflow:
   profileurl: https://stackoverflow.com/users/23371241/argus-magic
   flairimageurl: https://lh3.googleusercontent.com/a/ACg8ocKQJv8GNjS6Ncri_-Wxtzv1wcvIHGRrK_ru6ZsuEitwhQ=k-s256

# Intro section
intro: |
  I am a Physics Engineering student at the Autonomous University of San Luis Potosí (UASLP). My experience there amounts to learning, designing, and building projects around programming, web development, optics, electronics, and chemistry. Generally my outputs combine a mix of code, hands-on experiments, and mathematical analysis of physical phenomena.
  <br/><br/>
  Other than science I also enjoy making, listening, and performing music. I have been part of many musical projects throughout the years, mixing and producing music. As of now my band's music is primarily based on my own compositions and arrangements, and is only available to listen on YouTube <a target="_blank" href="https://www.youtube.com/@%C6%8EXHME">here</a>.
  <br/><br/>
  Finally I have also a range of side projects and hobbies that I tend to such as building open source tools (mostly for my personal use), reading on any kind of literature that crosses my path from economic theory to science fiction, playing videogames, and spending time with family and friends.

# Additional info section
additionalinfo: |
   <strong>Languages</strong>: Spanish (native), English (fluent/C2), German (B1).
   <br/>
   <strong>Hobbies</strong>: Music, Reading, Videogames, Boardgames
   <br/>
   <strong>Interests</strong>: Physics, Electronics, Programming
   <br/>
   <strong>Projects</strong>:
   <ul>
     <li>Built a basic 3D wireframe visualizer in C using the Allegro library</li>
     <li>Built a real-time signal analyzer and processor in Python based on Principles of the Fourier and Wavelet Transforms using the PyAudio and PyGame libraries</li>
     <li>Built a functioning graphic user interfase for the YT-DLP helper using Tkinter and BASH</li>
     <li>Used VHDL and the Quartus II software to build arithmetic logic units for a FPGA board</li>
     <li>Built and programmed a wireless bluetooth remote control car supported by the UART protocol in VHDL</li>
     <li>Designed and built various guitar effects stompboxes</li>
     <li>Composed, recorded, and mixed a variety of demo tapes</li>
   </ul>